---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: logging
spec:
  ports: 
    - port: 5044
      targetPort: beats
  selector:
    type: logstash
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: logstash
  namespace: logging
spec:
  selector:
    matchLabels: 
      type: logstash
  template:
    metadata:
      labels:
        type: logstash
        srv: srv-logstash
    spec:
      containers:
      - image: docker.io/kubeimages/logstash:7.9.3
        name: logstash
        ports: 
        - containerPort: 5044
          name: beats
        command:
        - logstash
        - '-f'
        - '/etc/logstash_c/logstash.conf'
        env:
        - name: "XPACK_MONITORING_ELASTICSEARCH_HOSTS"
          value: "http://elasticsearch:9200"
        volumeMounts:
        - name: config-volume 
          mountPath: /etc/logstash_c/
        - name: config-yml-volume
          mountPath: /usr/share/logstash/config/
        - name: timezone
          mountPath: /etc/localtime
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 512m
            memory: 512Mi
      volumes:
      - name: config-volume 
        configMap: 
          name: logstash-conf
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: timezone
        hostPath:
          path: /etc/localtime
      - name: config-yml-volume
        configMap:
          name: logstash-yml
          items: 
          - key: logstash.yml
            path: logstash.yml

