apiVersion: apps/v1 #版本号, 不同K8s版本api会有区别，确定版本功能所提供的api, kubectl api-resources
kind: Deployment #类型
metadata:
  name: nginx-deployment #元数据名称
spec: #详细描述
  selector: #选择器，通过它指定该控制器管理哪些pod
    matchLabels:
      app: nginx
  replicas: 2 #副本
  strategy: #策略
    type: RollingUpdate  #滚动更新策略 or Recreate
  template: #创建pod模版
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80