apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang 
  namespace: bullet 
spec:
  selector:
    matchLabels:
      app: golang 
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang 
        image: 19840112/golang:t1
