apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq 
  namespace: bullet 
spec:
  selector:
    matchLabels:
      app: mq 
  template:
    metadata:
      labels:
        app: mq 
    spec:
      containers:
      - name: push 
        image: rabbitmq:management
        ports:
        - name: http
          containerPort: 5672  # HTTP端口
        - name: other
          containerPort: 1234  # 第二个端口，你可以根据需要修改端口号
---

apiVersion: v1
kind: Service
metadata:
  name: mq
  namespace: bullet
spec:
  selector:
    app: mq 
  type: ClusterIP
  ports:
  - name: http
    port: 5672
    targetPort: 5672 
  - name: other
    port: 1234
    targetPort: 1234  # 这里对应 Deployment 中的第二个端口

