apiVersion: apps/v1
kind: Deployment
metadata:
  name: push 
  namespace: bullet 
spec:
  selector:
    matchLabels:
      app: push 
  template:
    metadata:
      labels:
        app: push
    spec:
      containers:
      - name: push 
        image: 19840112/push:v2
        ports:
        - containerPort: 8080  
---

apiVersion: v1
kind: Service
metadata:
  name: push
  namespace: bullet
spec:
  selector:
    app: push 
  type: ClusterIP
  ports:
    - port: 80   # 服务暴露的端口
      targetPort: 8080  # 服务的目标端口
      protocol: TCP
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: push 
  namespace: bullet
spec:
  ingressClassName: "nginx"
  rules:
  - host: push.errorstaff.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: push 
            port:
              number: 80
