apiVersion: apps/v1
kind: Deployment
metadata:
  name: rece 
  namespace: bullet 
spec:
  selector:
    matchLabels:
      app: rece 
  template:
    metadata:
      labels:
        app: rece
    spec:
      containers:
      - name: rece 
        image: 19840112/rece:v2
        ports:
        - name: other
          containerPort: 1234  # 第二个端口，你可以根据需要修改端口号
---

apiVersion: v1
kind: Service
metadata:
  name: rece
  namespace: bullet
spec:
  selector:
    app: rece 
  type: ClusterIP
  ports:
    - port: 80   # 服务暴露的端口
      targetPort: 1234  # 服务的目标端口
      protocol: TCP
      name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rece 
  namespace: bullet
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "rece"
spec:
  ingressClassName: "nginx"
  rules:
  - host: ws.errorstaff.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rece 
            port:
              number: 80
