apiVersion: v1
kind: PersistentVolume
metadata:
  name: hyperf
  labels:
    type: hyperf
  namespace: hyperf
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/.jenkins/workspace/hyperf
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node3
---
