apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hyperf-pv-claim
  labels:
    app: hyperf
  namespace: hyperf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
