apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
  namespace: logging
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/data/logstash" # 指定一個真實存在的路徑
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

