apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-dep
  name: wp-dep
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-dep
  template:
    metadata:
      labels:
        app: wp-dep
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql.db
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: 1qaz2wsx. 
        - name: WORDPRESS_DB_NAME
          value: wordpress
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-svc
  name: wp-svc
  namespace: wp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wp-dep
  type: ClusterIP
