apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: php
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      schema_config:
        configs:
          - from: 2020-01-01
            store: boltdb
            object_store: filesystem
            schema: v9
            index:
              prefix: index_
              period: 24h
        labels:
          job: php_logs
          log_type: application_log
---

