apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-php
  labels:
    type: local
  namespace: php
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/php/james
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-php
  labels:
    type: local
  namespace: php
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/php/james/storage/logs
