---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-pv-claim
  labels:
    app: log
  namespace: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---

