apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo-2
  namespace: default
  labels:  # 添加 labels
    app: configmap-demo
data:
  httpd_port: "8080"
  verbose_level: "-vv"
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-demo
  namespace: default
spec:
  containers:
  - image: evelynocean/hello:v1.0.0
    name: hello
    command: ["./hello"]
    args: ["-p","$(HTTPD_PORT)"]
    envFrom:  # 使用 envFrom
    - configMapRef:
        name: configmap-demo-2
        optional: false

